import { createElement } from '@lwc/engine-dom';
import FlightResultCard from 'c/flightResultCard';

describe('c-flight-result-card', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-flight-result-card', {
            is: FlightResultCard
        });

        element.offer = {
            airline: 'Indigo',
            flightNumber: '6E-123',
            price: 4000 ,
            origin: 'DEL',
            destination: 'BOM',
            cabinClass: 'Economy'
        };
        element.passengers = [{ name: 'Akarsh' }];

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});